services:
  traefik:
    image: "traefik:v3.5"
    container_name: "traefik-proxy"
    env_file: .env # <-- Loads the variables from traefik/.env
    environment:
      # This securely passes the token from the .env file
      # into the container's environment
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      # --- API, Providers, & Dynamic Config ---
      - "--api.dashboard=true" # Enables the web dashboard
      - "--providers.docker=true" # Tells Traefik to watch Docker
      - "--providers.docker.exposedbydefault=false" # CRITICAL: Don't expose any container unless it has a label
      - "--providers.docker.network=traefik-public" # CRITICAL: Only watch containers on this network
      - "--providers.file.directory=/dynamic_conf" # Load middlewares.yml

      # --- Enable Prometheus Metrics ---
      - "--metrics.prometheus=true" # Creates a /metrics endpoint
      - "--metrics.prometheus.entrypoint=metrics" # Makes it available on the 'metrics' entrypoint

      # --- Entrypoints (Ports) ---
      - "--entrypoints.web.address=:80" # For HTTP traffic
      - "--entrypoints.websecure.address=:443" # For HTTPS traffic
      - "--entrypoints.metrics.address=:8082" # For Prometheus (internal only)

      # --- Global HTTP to HTTPS Redirect ---
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # --- Let's Encrypt (ACME) with DNS-01 Challenge ---
      - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}" # Uses your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Where to save certs
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true" # Use DNS-01
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare" # Use Cloudflare

      # --- Wildcard Certificate Request ---
      # This is the KEY to our whole setup. It asks for ONE cert
      # that covers your main domain and ALL subdomains.
      - "--certificatesresolvers.myresolver.acme.domains[0].main=${MY_DOMAIN}"
      - "--certificatesresolvers.myresolver.acme.domains[0].sans=*.${MY_DOMAIN}"

      # --- Attach the resolver to our HTTPS entrypoint ---
      # This tells all traffic on port 443 to use our new wildcard cert
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"

    ports:
      # Maps your server's public ports to the container's entrypoints
      - "80:80"   # (web)
      - "443:443" # (websecure)
      # We DO NOT map 8082, keeping our metrics private.

    volumes:
      # Gives Traefik permission to listen to Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # A persistent volume to save our SSL certificates
      - "traefik-certs:/letsencrypt"
      # Mounts our middleware file so Traefik can read it
      - "./dynamic_conf:/dynamic_conf:ro"

    networks:
      # Connects Traefik to the main public network
      - traefik-public

    labels:
      # --- Secure the Dashboard ---
      # Yes, we use labels to tell Traefik how to configure *itself*
      - "traefik.enable=true" # Tell Traefik to expose this container
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${MY_DOMAIN}`)" # URL for the dashboard
      - "traefik.http.routers.traefik-dashboard.service=api@internal" # Special service for the dashboard
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure" # HTTPS only
      - "traefik.http.routers.traefik-dashboard.middlewares=authelia-auth@file,sec-headers@file" # Secure it!

volumes:
  traefik-certs: # Defines the persistent volume for certs